version: 2
updates:
  # Update npm/pnpm dependencies (both dependencies and devDependencies)
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "23:59"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - dependencies
    commit-message:
      prefix: "chore"
      include: scope
