name: Update CHANGELOG on Tag

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

env:
  NODE_VERSION: "24.3.0"
  PNPM_VERSION: "10.12.4"

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate CHANGELOG for latest release range
        run: pnpm changelog && pnpm format

      - name: Commit and push changes
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          if ! git diff --quiet -- CHANGELOG.md; then
            git add CHANGELOG.md
            git commit -m "chore: update CHANGELOG for ${{ github.ref_name }}"
            git push
          else
            echo "No CHANGELOG changes to commit."
          fi
